/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyaero;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author carlo
 */
public class FrmMenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuAdmin
     */
    public FrmMenuAdmin() throws FileNotFoundException, IOException {
        initComponents();
        IniciarPantalla();
        ScrollVuelos.setVisible(true);
        ScrollBoletos.setVisible(false);
        ScrollAviones.setVisible(false);
        lblTituloTabla.setVisible(true);
        File AvionesDB = new File("AvionesDB.txt"); //crea archivo aviones
        File VuelosDB = new File("VuelosDB.txt");   //crea archivo vuelos
        File BoletosDB = new File("BoletosDB.txt");
        FileReader lectorAviones = new FileReader(AvionesDB);        //crea un Lector para Aviones
        BufferedReader lectorBRAviones = new BufferedReader(lectorAviones);  
        FileReader lectorVuelos = new FileReader(VuelosDB);        //crea un Lector para Vuelos
        BufferedReader lectorBRVuelos = new BufferedReader(lectorVuelos);  
        FileReader lectorBoletos = new FileReader(BoletosDB);        //crea un Lector para Boletos
        BufferedReader lectorBRBoletos = new BufferedReader(lectorBoletos);
        DefaultTableModel ModeloAviones = (DefaultTableModel)tblAviones.getModel();
        String line=null;
        while ((line = lectorBRAviones.readLine()) != null) {
            String[] data = line.split(",");
            
            String Dato1= data[0];
            String Dato2= data[1];
            ModeloAviones.addRow(new Object[] {Dato1,Dato2});   
        }
        DefaultTableModel ModeloVuelos = (DefaultTableModel)tblVuelos.getModel();
        while ((line = lectorBRVuelos.readLine()) != null) {
            String[] data = line.split(",");
            
            String Dato1= data[0];
            String Dato2= data[1];
            String Dato3= data[2];
            String Dato4= data[3];
            String Dato5= data[4];
            String Dato6= data[5];
            ModeloVuelos.addRow(new Object[] {Dato1,Dato2,Dato3,Dato4,Dato5,Dato6});   
        }
        DefaultTableModel ModeloBoletos = (DefaultTableModel)tblBoletos.getModel();
        while ((line = lectorBRBoletos.readLine()) != null) {
            String[] data = line.split(",");
            
            String Dato1= data[0];
            String Dato2= data[1];
            String Dato3= data[2];
            String Dato4= data[3];
            ModeloBoletos.addRow(new Object[] {Dato1,Dato2,Dato3,Dato4});   
        }

       
        
    }
    
    public void IniciarPantalla() throws FileNotFoundException, IOException{
        //los botones iniciales
        btnAgregar.setVisible(false);
        btnModificar.setVisible(false);
        btnEliminar.setVisible(false);
        btnCancelar.setVisible(false);
        btnAgregarElemento.setVisible(true);
        btnModificarElemento.setVisible(true);
        btnEliminarElemento.setVisible(true);
        //Titulos
        lblTitulo.setText("Opciones de BD");
        //Opciones de datos 1,2,3
        txtDato1.setVisible(false);
        txtDato2.setVisible(false);
        txtDato3.setVisible(false);
        txtDato4.setVisible(false);
        txtDato5.setVisible(false);
        lblDato1.setVisible(false);
        lblDato2.setVisible(false);
        lblDato3.setVisible(false);
        lblDato4.setVisible(false);
        lblDato5.setVisible(false);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollBoletos = new javax.swing.JScrollPane();
        tblBoletos = new javax.swing.JTable();
        ScrollAviones = new javax.swing.JScrollPane();
        tblAviones = new javax.swing.JTable();
        ScrollVuelos = new javax.swing.JScrollPane();
        tblVuelos = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        lblTituloTabla = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        txtDato1 = new javax.swing.JTextField();
        txtDato2 = new javax.swing.JTextField();
        txtDato3 = new javax.swing.JTextField();
        lblDato1 = new javax.swing.JLabel();
        lblDato2 = new javax.swing.JLabel();
        lblDato3 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnEliminarElemento = new javax.swing.JButton();
        btnModificarElemento = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnAgregarElemento = new javax.swing.JButton();
        lblDato4 = new javax.swing.JLabel();
        txtDato4 = new javax.swing.JTextField();
        lblDato5 = new javax.swing.JLabel();
        txtDato5 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuOpcionesDB = new javax.swing.JMenu();
        MenuPanAviones = new javax.swing.JMenuItem();
        MenuPanVuelos = new javax.swing.JMenuItem();
        MenuPanBoletos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(50, 50));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblBoletos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Nombre", "#Vuelo", "Asiento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollBoletos.setViewportView(tblBoletos);

        getContentPane().add(ScrollBoletos, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 50, 410, 450));

        tblAviones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollAviones.setViewportView(tblAviones);
        if (tblAviones.getColumnModel().getColumnCount() > 0) {
            tblAviones.getColumnModel().getColumn(0).setResizable(false);
            tblAviones.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(ScrollAviones, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 50, 410, 450));

        tblVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "Origen", "Destino", "FechaSalida", "HoraSalida", "HoraLlegada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollVuelos.setViewportView(tblVuelos);

        getContentPane().add(ScrollVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 50, 410, 450));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 20, 10, 480));

        lblTituloTabla.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTituloTabla.setText("Tabla de vuelos");
        getContentPane().add(lblTituloTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 230, 50));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setText("Opciones de BD");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 50));

        txtDato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDato1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtDato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 130, -1));
        getContentPane().add(txtDato2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 130, -1));
        getContentPane().add(txtDato3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 130, -1));

        lblDato1.setText("Dato1");
        getContentPane().add(lblDato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        lblDato2.setText("Dato2");
        getContentPane().add(lblDato2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));

        lblDato3.setText("Dato3");
        getContentPane().add(lblDato3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 20));

        btnSalir.setText("Cerrar Sesion");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 475, 210, -1));

        btnEliminarElemento.setText("Eliminar Vuelo");
        btnEliminarElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarElementoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarElemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 90, 140, -1));

        btnModificarElemento.setText("Modificar Vuelo");
        btnModificarElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarElementoActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificarElemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 120, 140, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 100, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 100, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 102, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 439, 100, -1));

        btnAgregarElemento.setText("Agregar Vuelo");
        btnAgregarElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarElementoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarElemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 60, 140, -1));

        lblDato4.setText("Dato5");
        getContentPane().add(lblDato4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));
        getContentPane().add(txtDato4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 130, -1));

        lblDato5.setText("Dato6");
        getContentPane().add(lblDato5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 20));
        getContentPane().add(txtDato5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 130, -1));

        MenuOpcionesDB.setText("Mostrar Tablas");
        MenuOpcionesDB.setToolTipText("");

        MenuPanAviones.setText("Tabla de Aviones");
        MenuPanAviones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPanAvionesActionPerformed(evt);
            }
        });
        MenuOpcionesDB.add(MenuPanAviones);

        MenuPanVuelos.setText("Tabla de Vuelos");
        MenuPanVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPanVuelosActionPerformed(evt);
            }
        });
        MenuOpcionesDB.add(MenuPanVuelos);

        MenuPanBoletos.setText("Tabla de Boletos");
        MenuPanBoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPanBoletosActionPerformed(evt);
            }
        });
        MenuOpcionesDB.add(MenuPanBoletos);

        jMenuBar1.add(MenuOpcionesDB);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuPanAvionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPanAvionesActionPerformed
        lblTituloTabla.setVisible(true);
        lblTituloTabla.setText("Tabla Aviones");
        ScrollAviones.setVisible(true);
        ScrollVuelos.setVisible(false);
        ScrollBoletos.setVisible(false);
        btnAgregarElemento.setText("Agregar Avion");
        btnModificarElemento.setText("Modificar Avion");
        btnEliminarElemento.setText("Eliminar Avion");
    }//GEN-LAST:event_MenuPanAvionesActionPerformed

    private void MenuPanVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPanVuelosActionPerformed
        lblTituloTabla.setVisible(true);
        lblTituloTabla.setText("Tabla Vuelos");
        ScrollVuelos.setVisible(true);
        ScrollBoletos.setVisible(false);
        ScrollAviones.setVisible(false);
        btnAgregarElemento.setText("Agregar Vuelo");
        btnModificarElemento.setText("Modificar Vuelo");
        btnEliminarElemento.setText("Eliminar Vuelo");
    }//GEN-LAST:event_MenuPanVuelosActionPerformed

    private void MenuPanBoletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPanBoletosActionPerformed
        lblTituloTabla.setVisible(true);
        lblTituloTabla.setText("Tabla Boletos");
        ScrollBoletos.setVisible(true);
        ScrollAviones.setVisible(false);
        ScrollVuelos.setVisible(false);
        btnAgregarElemento.setText("Agregar Boletos");
        btnModificarElemento.setText("Modificar Boletos");
        btnEliminarElemento.setText("Eliminar Boletos");
    }//GEN-LAST:event_MenuPanBoletosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
        new FrmLogin().setVisible(true); 
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        try {
            IniciarPantalla();
        } catch (IOException ex) {
            Logger.getLogger(FrmMenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarElementoActionPerformed
        btnAgregar.setVisible(true);
        btnModificar.setVisible(false);
        btnEliminar.setVisible(false);
        btnCancelar.setVisible(true);
        lblTitulo.setText("Menu de Agregado");
        btnAgregarElemento.setVisible(false);
        btnModificarElemento.setVisible(false);
        btnEliminarElemento.setVisible(false);
        if (ScrollBoletos.isVisible()){
            //set lables
            lblDato1.setVisible(true);
            lblDato2.setVisible(true);
            lblDato3.setVisible(true);
            //set txts
            txtDato1.setVisible(true);
            txtDato2.setVisible(true);
            txtDato3.setVisible(true);
            //set txt text
            lblDato1.setText("Nombre");
            lblDato2.setText("#vuelo");
            lblDato3.setText("Asiento");
        }
        if (ScrollVuelos.isVisible()){
            //set lables
            lblDato1.setVisible(true);
            lblDato2.setVisible(true);
            lblDato3.setVisible(true);
            lblDato4.setVisible(true);
            lblDato5.setVisible(true);
            //set txts
            txtDato1.setVisible(true);
            txtDato2.setVisible(true);
            txtDato3.setVisible(true);
            txtDato4.setVisible(true);
            txtDato5.setVisible(true);
            //set txt text
            lblDato1.setText("Origen");
            lblDato2.setText("Destino");
            lblDato3.setText("FechaSalida");
            lblDato4.setText("HoraSalida");
            lblDato5.setText("HoraLlegada");
            
        }
        if (ScrollAviones.isVisible()){
            //set lables
            lblDato1.setVisible(true);
            //set txts
            txtDato1.setVisible(true);
            //set txt text
            lblDato1.setText("Nombre Avion");
        }
    }//GEN-LAST:event_btnAgregarElementoActionPerformed

    private void btnEliminarElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarElementoActionPerformed
        btnAgregar.setVisible(false);
        btnModificar.setVisible(false);
        btnEliminar.setVisible(true);
        btnCancelar.setVisible(true);
        lblTitulo.setText("Menu de Eliminado");
        btnAgregarElemento.setVisible(false);
        btnModificarElemento.setVisible(false);
        btnEliminarElemento.setVisible(false);
        //botones
        lblDato1.setVisible(true);
        txtDato1.setVisible(true);
        lblDato1.setText("Id a Eliminar");

    }//GEN-LAST:event_btnEliminarElementoActionPerformed

    private void txtDato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDato1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDato1ActionPerformed

    private void btnModificarElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarElementoActionPerformed
        btnAgregar.setVisible(false);
        btnModificar.setVisible(true);
        btnEliminar.setVisible(false);
        btnCancelar.setVisible(true);
        lblTitulo.setText("Menu de Modificacion");
        btnAgregarElemento.setVisible(false);
        btnModificarElemento.setVisible(false);
        btnEliminarElemento.setVisible(false);
        //botones
        lblDato1.setVisible(true);
        txtDato1.setVisible(true);
        lblDato1.setText("Id a Eliminar");
    }//GEN-LAST:event_btnModificarElementoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuOpcionesDB;
    private javax.swing.JMenuItem MenuPanAviones;
    private javax.swing.JMenuItem MenuPanBoletos;
    private javax.swing.JMenuItem MenuPanVuelos;
    private javax.swing.JScrollPane ScrollAviones;
    private javax.swing.JScrollPane ScrollBoletos;
    private javax.swing.JScrollPane ScrollVuelos;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarElemento;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarElemento;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificarElemento;
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDato1;
    private javax.swing.JLabel lblDato2;
    private javax.swing.JLabel lblDato3;
    private javax.swing.JLabel lblDato4;
    private javax.swing.JLabel lblDato5;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloTabla;
    private javax.swing.JTable tblAviones;
    private javax.swing.JTable tblBoletos;
    private javax.swing.JTable tblVuelos;
    private javax.swing.JTextField txtDato1;
    private javax.swing.JTextField txtDato2;
    private javax.swing.JTextField txtDato3;
    private javax.swing.JTextField txtDato4;
    private javax.swing.JTextField txtDato5;
    // End of variables declaration//GEN-END:variables
}
