/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyaero;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.WriterException;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Hashtable;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author HP
 */
public class FrmPagar extends javax.swing.JFrame {
    /**
     * Creates new form FrmPagar
     */
    public FrmPagar() {
        initComponents();
    }

    FrmPagar(FrmComprar aThis) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void setTextFieldData(String data1, String selectedOption, String data2, String data3, String data4 ) {
        TxtMostrarV.setText(data1);
        TxtTipoV.setText(selectedOption);
        TxtPrecioV.setText(data2);
        TxtPasajeroV.setText(data3);
        TxtTotalV.setText(data4);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCompraVuelo = new javax.swing.JLabel();
        BtnSali = new javax.swing.JButton();
        TxtMostrarV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtTipoV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtPrecioV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtPasajeroV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtTotalV = new javax.swing.JTextField();
        LblQR = new javax.swing.JLabel();
        BtnQR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCompraVuelo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCompraVuelo.setText("Pago del Vuelo");
        getContentPane().add(lblCompraVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, -1, -1));

        BtnSali.setText("Salir");
        BtnSali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaliActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSali, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));
        getContentPane().add(TxtMostrarV, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 50, 490, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tu vuelo es:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 50, -1, 30));
        getContentPane().add(TxtTipoV, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 90, 110, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tipo de vuelo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 90, -1, 30));
        getContentPane().add(TxtPrecioV, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 90, 80, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Pasajeros:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 130, -1, 30));
        getContentPane().add(TxtPasajeroV, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 130, 50, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Total:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 170, -1, 30));
        getContentPane().add(TxtTotalV, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 170, 70, -1));
        getContentPane().add(LblQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 95, 210, 200));

        BtnQR.setText("Generar QR");
        BtnQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnQRActionPerformed(evt);
            }
        });
        getContentPane().add(BtnQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyaero/Pagos.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaliActionPerformed
        FrmLogin objLogin = new FrmLogin();
        this.setVisible(false);
        objLogin.setVisible(true);
    }//GEN-LAST:event_BtnSaliActionPerformed

    private void BtnQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnQRActionPerformed
        try {
            String data1 = TxtMostrarV.getText();
            String data2 = TxtTipoV.getText();
            String data3 = TxtPrecioV.getText();
            String data4 = TxtPasajeroV.getText();
            String data5 = TxtTotalV.getText();
            String combinedData = data1 + "\n" + data2 + "\n" + data3 + "\n" + data4 + "\n" + data5;

            int size = 220;
            Hashtable<EncodeHintType, Object> hints = new Hashtable<>();
            hints.put(EncodeHintType.CHARACTER_SET, "UTF-8");
            BitMatrix bitMatrix = new QRCodeWriter().encode(combinedData, BarcodeFormat.QR_CODE, size, size, hints);

            BufferedImage image = new BufferedImage(size, size, BufferedImage.TYPE_INT_RGB);
            image.createGraphics();

            Graphics2D graphics = (Graphics2D) image.getGraphics();
            graphics.setColor(Color.WHITE);
            graphics.fillRect(0, 0, size, size);
            graphics.setColor(Color.BLACK);

            for (int i = 0; i < size; i++) {
                for (int j = 0; j < size; j++) {
                    if (bitMatrix.get(i, j)) {
                        graphics.fillRect(i, j, 1, 1);
                    }
                }
            }

            ImageIcon icon = new ImageIcon(image);
            LblQR.setIcon(icon);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_BtnQRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {  
                public void run() {
                new FrmPagar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnQR;
    private javax.swing.JButton BtnSali;
    private javax.swing.JLabel LblQR;
    private javax.swing.JTextField TxtMostrarV;
    private javax.swing.JTextField TxtPasajeroV;
    private javax.swing.JTextField TxtPrecioV;
    private javax.swing.JTextField TxtTipoV;
    private javax.swing.JTextField TxtTotalV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCompraVuelo;
    // End of variables declaration//GEN-END:variables

    private static class ImgeIcon {

        public ImgeIcon(String string) {
        }

        private Image getImage() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
